name: easy_paging
resolution: workspace
description: Pagination widgets built on top of easy_refresh.
version: 4.0.0
homepage: https://xuelongqy.github.io/flutter_easy_refresh
repository: https://github.com/xuelongqy/flutter_easy_refresh
issue_tracker: https://github.com/xuelongqy/flutter_easy_refresh/issues

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  easy_refresh: ^4.0.0
  material_ui: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
