name: flutter_easy_refresh
workspace:
  - example
  - packages/easy_refresh
  - packages/easy_paging
  - packages/easy_refresh_bubbles
  - packages/easy_refresh_bow
  - packages/easy_refresh_halloween
  - packages/easy_refresh_skating
  - packages/easy_refresh_space
  - packages/easy_refresh_squats

environment:
  sdk: ">=3.6.0 <4.0.0"

dev_dependencies:
  melos: ^7.4.0
