name: easy_refresh_bow
description: Bow Indicator on EasyRefresh. Provides BowHeader and BowFooter. Animation with Rive.
resolution: workspace
version: 1.1.1
homepage: https://xuelongqy.github.io/flutter_easy_refresh/#/style/bow
repository: https://github.com/xuelongqy/flutter_easy_refresh
issue_tracker: https://github.com/xuelongqy/flutter_easy_refresh/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.24.0"

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.14.4
  easy_refresh: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
 assets:
   - assets/bow.riv
